
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Feb 10 03:44:41 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 9;
  public static final int CHAR = 41;
  public static final int CONST = 5;
  public static final int CONTINUE = 43;
  public static final int LPAREN = 11;
  public static final int GREATER = 31;
  public static final int SEMI = 6;
  public static final int LESS = 33;
  public static final int MINUS = 27;
  public static final int RPAREN = 12;
  public static final int AND = 22;
  public static final int OR = 23;
  public static final int COMMA = 7;
  public static final int INC = 20;
  public static final int DIV = 36;
  public static final int LESS_EQUAL = 34;
  public static final int DIFFERENT = 30;
  public static final int PLUS = 26;
  public static final int IF = 14;
  public static final int BOOLEAN = 40;
  public static final int EOF = 0;
  public static final int RETURN = 44;
  public static final int RBRACKET = 10;
  public static final int EQUAL = 8;
  public static final int GREATER_EQUAL = 32;
  public static final int NEW = 28;
  public static final int error = 1;
  public static final int MUL = 35;
  public static final int DOUBLE_EQUAL = 29;
  public static final int NUMBER = 39;
  public static final int MOD = 37;
  public static final int BREAK = 42;
  public static final int IDENT = 38;
  public static final int VOID = 13;
  public static final int COLON = 24;
  public static final int LBRACE = 3;
  public static final int ELSE = 15;
  public static final int READ = 18;
  public static final int WHILE = 17;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int QUESTION = 25;
  public static final int DEC = 21;
  public static final int PRINT = 19;
  public static final int DO = 16;
}

